//subject
export const GET_SUBJECTS_SUCCESS = 'GET_SUBJECTS_SUCCESS';
export const ADD_SUBJECT_SUCCESS = 'ADD_SUBJECT_SUCCESS';
export const DELETE_SUBJECT_SUCCESS = 'DELETE_SUBJECT_SUCCESS';

//task
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS';

//dialogs
export const CHANGE_ADD_DIALOG_VISIBILITY = 'CHANGE_ADD_DIALOG_VISIBILITY'
export const CHANGE_DELETE_DIALOG_VISIBILITY = 'CHANGE_DELETE_DIALOG_VISIBILITY'
export const CHANGE_TASK_DIALOG_VISIBILITY = 'CHANGE_TASK_DIALOG_VISIBILITY'
export const CHANGE_GROUP_DIALOG_VISIBILITY = 'CHANGE_GROUP_DIALOG_VISIBILITY'
export const CHANGE_EDIT_USER_DIALOG_VISIBILITY = 'CHANGE_EDIT_USER_DIALOG_VISIBILITY'
export const CHANGE_DELETE_USER_DIALOG_VISIBILITY= 'CHANGE_DELETE_USER_DIALOG_VISIBILITY'
export const CHANGE_ADMIN_ADD_SUBJECT_DIALOG_VISIBILITY= 'CHANGE_ADMIN_ADD_SUBJECT_DIALOG_VISIBILITY'
export const CHANGE_ADMIN_DELETE_SUBJECT_DIALOG_VISIBILITY = 'CHANGE_ADMIN_DELETE_SUBJECT_DIALOG_VISIBILITY'
export const CHANGE_ADMIN_ADD_TASK_DIALOG_VISIBILITY = 'CHANGE_ADMIN_ADD_TASK_DIALOG_VISIBILITY'
export const CHANGE_ADMIN_EDIT_TASK_DIALOG_VISIBILITY = 'CHANGE_ADMIN_EDIT_TASK_DIALOG_VISIBILITY'
export const CHANGE_ADMIN_DELETE_TASK_DIALOG_VISIBILITY = 'CHANGE_ADMIN_DELETE_TASK_DIALOG_VISIBILITY'
export const CHANGE_MANAGE_ROLES_DIALOG_VISIBILITY = 'CHANGE_MANAGE_ROLES_DIALOG_VISIBILITY'
export const CHANGE_ADMIN_MANAGE_GROUP_DIALOG_VISIBILITY = 'CHANGE_ADMIN_MANAGE_GROUP_DIALOG_VISIBILITY'
export const CHANGE_ADD_TEST_DIALOG_VISIBILITY = 'CHANGE_ADD_TEST_DIALOG_VISIBILITY'
export const CHANGE_NEW_TEST_TYPE = 'CHANGE_NEW_TEST_TYPE'
export const CHANGE_ADMIN_ADD_GROUP_DIALOG_VISIBILITY = 'CHANGE_ADMIN_ADD_GROUP_DIALOG_VISIBILITY'
export const CHANGE_ADMIN_EDIT_GROUP_DIALOG_VISIBILITY = 'CHANGE_ADMIN_EDIT_GROUP_DIALOG_VISIBILITY'
export const CHANGE_ADMIN_DELETE_GROUP_DIALOG_VISIBILITY = 'CHANGE_ADMIN_DELETE_GROUP_DIALOG_VISIBILITY'

//login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

//registration
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';

//groups
export const ASSIGN_GROUP_SUCCESS = 'ASSIGN_GROUP_SUCCESS';
export const ASSIGN_GROUP_FAILED = 'ASSIGN_GROUP_FAILED';
export const UNASSIGN_GROUP_SUCCESS = 'UNASSIGN_GROUP_SUCCESS';
export const UNASSIGN_GROUP_FAILED = 'UNASSIGN_GROUP_FAILED';
export const GET_GROUPS_SUCCESS = 'GET_GROUPS_SUCCESS';

//users
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'

//user details
export const GET_ALL_SUBJECTS_SUCCESS = 'GET_ALL_SUBJECTS_SUCCESS'
export const GET_ALL_TEACHES_SUCCESS = 'GET_ALL_TEACHES_SUCCESS'
export const ADMIN_ADD_SUBJECT_SUCCESS = 'ADMIN_ADD_SUBJECT_SUCCESS'
export const CHANGE_ADMIN_EDIT_SUBJECT_DIALOG_VISIBILITY = 'CHANGE_ADMIN_EDIT_SUBJECT_DIALOG_VISIBILITY'
export const ADMIN_EDIT_SUBJECT_SUCCESS = 'ADMIN_EDIT_SUBJECT_SUCCESS'
export const ADMIN_DELETE_SUBJECT_SUCCESS = 'ADMIN_DELETE_SUBJECT_SUCCESS'

//tasks
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS'
export const GET_ADMIN_ALL_SUBJECTS_SUCCESS = 'GET_ALL_SUBJECTS_SUCCESS'
export const GET_ADMIN_ALL_USERS_SUCCESS = 'GET_ADMIN_ALL_USERS_SUCCESS'
export const USER_ID_CHANGED = 'USER_ID_CHANGED'
export const ADMIN_ADD_TASK_SUCCESS = 'ADMIN_ADD_TASK_SUCCESS'
export const ADMIN_EDIT_TASK_SUCCESS = 'ADMIN_EDIT_TASK_SUCCESS'
export const ADMIN_DELETE_TASK_SUCCESS = 'ADMIN_DELETE_TASK_SUCCESS'
export const GET_ROLES_SUCCESS = 'GET_ROLES_SUCCESS'
export const ASSIGN_ROLE_SUCCESS = 'ASSIGN_ROLE_SUCCESS'
export const UNASSIGN_ROLE_SUCCESS ='UNASSIGN_ROLE_SUCCESS'
export const GET_ADMIN_ALL_GROUPS_SUCCESS = 'GET_ADMIN_ALL_GROUPS_SUCCESS'
export const ASSIGN_ADMIN_GROUP_SUCCESS = 'ASSIGN_ADMIN_GROUP_SUCCESS'
export const UNASSIGN_ADMIN_GROUP_SUCCESS = 'UNASSIGN_ADMIN_GROUP_SUCCESS'
export const ADMIN_GET_GROUPS_SUCCESS = 'ADMIN_GET_GROUPS_SUCCESS'
export const ADD_GROUP_SUCCESS = 'ADD_GROUP_SUCCESS'
export const EDIT_GROUP_SUCCESS = 'EDIT_GROUP_SUCCESS'
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS'
