export const GET_SUBJECTS_SUCCESS = 'GET_SUBJECTS_SUCCESS';
export const ADD_SUBJECT_SUCCESS = 'ADD_SUBJECT_SUCCESS';
export const DELETE_SUBJECT_SUCCESS = 'DELETE_SUBJECT_SUCCESS';

export const CHANGE_ADD_DIALOG_VISIBILITY = 'CHANGE_ADD_DIALOG_VISIBILITY';
export const CHANGE_DELETE_DIALOG_VISIBILITY = 'CHANGE_DELETE_DIALOG_VISIBILITY';
