export const GET_SUBJECTS_SUCCESS = 'GET_SUBJECTS_SUCCESS';
export const ADD_SUBJECT_SUCCESS = 'ADD_SUBJECT_SUCCESS';

export const ADD_SUBJECT_REQUEST_START = 'ADD_SUBJECT_REQUEST_START';
export const ADD_SUBJECT_REQUEST_END = 'ADD_SUBJECT_REQUEST_END';
