CREATE TABLE [dbo].[UserGroups] (
    [Id]			UNIQUEIDENTIFIER		DEFAULT NEWID() PRIMARY KEY,
    [UserId]		UNIQUEIDENTIFIER		NOT NULL,
    [GroupId]		UNIQUEIDENTIFIER		NOT NULL,
    CONSTRAINT [UserGroup_Group] FOREIGN KEY ([GroupId]) REFERENCES [dbo].[Groups] ([Id]) ON DELETE CASCADE,
	CONSTRAINT [UserGroup_User] FOREIGN KEY ([UserId]) REFERENCES [dbo].[Users] ([Id]) ON DELETE CASCADE
);

