CREATE TABLE [dbo].[UserTask] (
	[Id] UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    [Task_Id] UNIQUEIDENTIFIER NOT NULL,
    [User_Id]   UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [UserTask_Task] FOREIGN KEY ([TAsk_Id]) REFERENCES [dbo].[Task] ([Id])
);

